[package]
name = "rustc-dependencies"
version = "0.0.0"
description = "TBD"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ra-ap-rustc_lexer = { version = "0.14.0" }
ra-ap-rustc_parse_format = { version = "0.14.0", default-features = false }
ra-ap-rustc_index = { version = "0.14.0", default-features = false }
ra-ap-rustc_abi = { version = "0.14.0", default-features = false }

in-tree-rustc_lexer = { path = "../../../../../compiler/rustc_lexer", package = "rustc_lexer" }
in-tree-rustc_parse_format = { path = "../../../../../compiler/rustc_parse_format", package = "rustc_parse_format", default-features = false }
in-tree-rustc_index = { path = "../../../../../compiler/rustc_index", package = "rustc_index", default-features = false }
in-tree-rustc_abi = { path = "../../../../../compiler/rustc_abi", package = "rustc_abi", default-features = false }

[features]
in-rust-tree = []
